#
# PrivateGlobal config for FlexGet
#

transmission:
  host: localhost
  port: 9091
  username: transmission
  password: transmission
  addpaused: yes

email:
  from: FromEmail@gmail.com
  to: ToEmal@gmail.com
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_username: FromUserName
  smtp_password: FromPassword
  smtp_tls: yes
